ME 374 search history
manga-easy/manga_easy_advanced_search pull request #3
Opened 2023-06-24 01:25 UTC by BrunoAlm

PR referente ao novo campo de histórico na tela de pesquisa avançada
![image](https://github.com/manga-easy/manga_easy_advanced_search/assets/65208006/3133fb57-1076-4bf6-9b89-bc00c73c19f9)

2023-06-24 17:47 UTC, cledsonv requested changes
Faltou tirar dependências que estão direto no path

2023-06-24 20:55 UTC, BrunoAlm commented
ainda falta subir a versão do coffee pra eu mudar nas dependências

2023-06-30 01:02 UTC, cledsonv approved these changes
Muito bom

2023-06-30 01:02 UTC, lucascardo12 approved these changes

2023-06-30 01:02 UTC, lucascardo12 commented on pubspec.yaml
> +  #   ref: v1.1.1
só não esquece de por as tags aqui.

2023-06-30 01:04 UTC, BrunoAlm commented on pubspec.yaml
> +  #   ref: v1.1.1
resolvido

2023-06-30 01:04 UTC, merged