ME-447 add lints
manga-easy/manga_easy_advanced_search pull request #6
Opened 2023-07-28 16:05 UTC by cledsonv

2023-07-29 00:26 UTC, BrunoAlm approved these changes

2023-08-19 00:22 UTC, lucascardo12 requested changes

2023-08-19 00:22 UTC, lucascardo12 commented on pubspec.yaml
> +  custom_lint: 0.5.0
esse aqui custom_lints não precisa pode tirar

2023-08-21 18:40 UTC, lucascardo12 approved these changes
Muito bom

2023-08-21 18:40 UTC, merged